spring.mvc.view.prefix=/WEB-INF/Views/
spring.mvc.view.suffix=.jsp
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/venue_seat_db
spring.datasource.username=root
spring.datasource.password=imal1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Application name
spring.application.name=EventBookingSystem

# JSP view resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# MySQL Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/event_ticket_booking
spring.datasource.username=root
spring.datasource.password=#Mixedfruit123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.security.enabled=false
# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/ticket_booking_db
spring.datasource.username=root
spring.datasource.password=2122


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp


spring.thymeleaf.view-names=th_*, layout/*, *.html, !bookingForm, !editBooking, !myBookings
# This tells Thymeleaf NOT to handle your JSP views
spring.thymeleaf.view-names=th_*, layout/*, *.html, !bookingForm, !editBooking, !myBookings
