spring.application.name=EventBookingSystem

# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/ticket_booking_db
spring.datasource.username=root
spring.datasource.password=2122

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JSP config
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# This tells Thymeleaf NOT to handle your JSP views
spring.thymeleaf.view-names=th_*, layout/*, *.html